<?php

namespace App\Repository;


use App\Entity\Categorie;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends ServiceEntityRepository
{

	public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Categorie::class);
    }


	public function loadCategorieByName($nom)
    {
        return $this->createQueryBuilder('cat')
            ->where('cat.nom = :nom')
            ->setParameter('nom', $nom)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
